controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_dashboard:
    path: /dashboard
    controller:  App\Controller\DashboardController::index

task_create:
    path: /task_create
    controller:  App\Controller\TaskController::create

